### Test GET /website using .rest extension
GET http://localhost:8383
### Test GET /website using .rest extension

GET http://localhost:8383/dashboard

###DATA ENDPOINT
GET http://localhost:8383/api/data

###Data endpoint for adding a user
POST http://localhost:8383/api/data
Content-Type: application/json

{
    "name":"Isagi Yoichi"

}

###
DELETE http://localhost:8383/api/data

